/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SelectRoleRouteImport } from './routes/select-role'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StartupsIdRouteImport } from './routes/startups/$id'
import { Route as InvestorWatchlistRouteImport } from './routes/investor/watchlist'
import { Route as InvestorPortfolioRouteImport } from './routes/investor/portfolio'
import { Route as InvestorMeetingsRouteImport } from './routes/investor/meetings'
import { Route as InvestorDueDiligenceRouteImport } from './routes/investor/due-diligence'
import { Route as InvestorDiscoverRouteImport } from './routes/investor/discover'
import { Route as InvestorDashboardRouteImport } from './routes/investor/dashboard'
import { Route as FounderPitchDecksRouteImport } from './routes/founder/pitch-decks'
import { Route as FounderMeetingsRouteImport } from './routes/founder/meetings'
import { Route as FounderDashboardRouteImport } from './routes/founder/dashboard'
import { Route as ApiMatchesRouteImport } from './routes/api/matches'
import { Route as ApiLogoutRouteImport } from './routes/api/logout'
import { Route as ApiLoginRouteImport } from './routes/api/login'
import { Route as ApiCallbackRouteImport } from './routes/api/callback'
import { Route as FounderStartupsIndexRouteImport } from './routes/founder/startups/index'
import { Route as ApiWatchlistIndexRouteImport } from './routes/api/watchlist/index'
import { Route as ApiStartupsIndexRouteImport } from './routes/api/startups/index'
import { Route as ApiPitchDeckIndexRouteImport } from './routes/api/pitch-deck/index'
import { Route as ApiNotificationsIndexRouteImport } from './routes/api/notifications/index'
import { Route as ApiMeetingsIndexRouteImport } from './routes/api/meetings/index'
import { Route as ApiConversationsIndexRouteImport } from './routes/api/conversations/index'
import { Route as StartupsIdDueDiligenceRouteImport } from './routes/startups/$id.due-diligence'
import { Route as StartupsIdChatRouteImport } from './routes/startups/$id.chat'
import { Route as FounderStartupsNewRouteImport } from './routes/founder/startups/new'
import { Route as ApiWatchlistIdRouteImport } from './routes/api/watchlist/$id'
import { Route as ApiStartupsDiscoverRouteImport } from './routes/api/startups/discover'
import { Route as ApiStartupsIdRouteImport } from './routes/api/startups/$id'
import { Route as ApiSettingsProfileRouteImport } from './routes/api/settings/profile'
import { Route as ApiPitchDeckUploadRouteImport } from './routes/api/pitch-deck/upload'
import { Route as ApiPitchDeckListRouteImport } from './routes/api/pitch-deck/list'
import { Route as ApiNotificationsIdRouteImport } from './routes/api/notifications/$id'
import { Route as ApiMeetingsIdRouteImport } from './routes/api/meetings/$id'
import { Route as ApiInvestorProfileRouteImport } from './routes/api/investor/profile'
import { Route as ApiFounderProfileRouteImport } from './routes/api/founder/profile'
import { Route as ApiAuthUserRouteImport } from './routes/api/auth/user'
import { Route as ApiAuthRoleRouteImport } from './routes/api/auth/role'
import { Route as FounderStartupsIdImproveRouteImport } from './routes/founder/startups/$id.improve'
import { Route as FounderStartupsIdEditRouteImport } from './routes/founder/startups/$id.edit'
import { Route as ApiStartupsIdImproveRouteImport } from './routes/api/startups/$id/improve'
import { Route as ApiStartupsIdChatRouteImport } from './routes/api/startups/$id/chat'
import { Route as ApiStartupsIdAnalyzeRouteImport } from './routes/api/startups/$id/analyze'
import { Route as ApiConversationsIdMessagesRouteImport } from './routes/api/conversations/$id/messages'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SelectRoleRoute = SelectRoleRouteImport.update({
  id: '/select-role',
  path: '/select-role',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StartupsIdRoute = StartupsIdRouteImport.update({
  id: '/startups/$id',
  path: '/startups/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestorWatchlistRoute = InvestorWatchlistRouteImport.update({
  id: '/investor/watchlist',
  path: '/investor/watchlist',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestorPortfolioRoute = InvestorPortfolioRouteImport.update({
  id: '/investor/portfolio',
  path: '/investor/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestorMeetingsRoute = InvestorMeetingsRouteImport.update({
  id: '/investor/meetings',
  path: '/investor/meetings',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestorDueDiligenceRoute = InvestorDueDiligenceRouteImport.update({
  id: '/investor/due-diligence',
  path: '/investor/due-diligence',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestorDiscoverRoute = InvestorDiscoverRouteImport.update({
  id: '/investor/discover',
  path: '/investor/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestorDashboardRoute = InvestorDashboardRouteImport.update({
  id: '/investor/dashboard',
  path: '/investor/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const FounderPitchDecksRoute = FounderPitchDecksRouteImport.update({
  id: '/founder/pitch-decks',
  path: '/founder/pitch-decks',
  getParentRoute: () => rootRouteImport,
} as any)
const FounderMeetingsRoute = FounderMeetingsRouteImport.update({
  id: '/founder/meetings',
  path: '/founder/meetings',
  getParentRoute: () => rootRouteImport,
} as any)
const FounderDashboardRoute = FounderDashboardRouteImport.update({
  id: '/founder/dashboard',
  path: '/founder/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMatchesRoute = ApiMatchesRouteImport.update({
  id: '/api/matches',
  path: '/api/matches',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLogoutRoute = ApiLogoutRouteImport.update({
  id: '/api/logout',
  path: '/api/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLoginRoute = ApiLoginRouteImport.update({
  id: '/api/login',
  path: '/api/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCallbackRoute = ApiCallbackRouteImport.update({
  id: '/api/callback',
  path: '/api/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const FounderStartupsIndexRoute = FounderStartupsIndexRouteImport.update({
  id: '/founder/startups/',
  path: '/founder/startups/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWatchlistIndexRoute = ApiWatchlistIndexRouteImport.update({
  id: '/api/watchlist/',
  path: '/api/watchlist/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStartupsIndexRoute = ApiStartupsIndexRouteImport.update({
  id: '/api/startups/',
  path: '/api/startups/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPitchDeckIndexRoute = ApiPitchDeckIndexRouteImport.update({
  id: '/api/pitch-deck/',
  path: '/api/pitch-deck/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNotificationsIndexRoute = ApiNotificationsIndexRouteImport.update({
  id: '/api/notifications/',
  path: '/api/notifications/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMeetingsIndexRoute = ApiMeetingsIndexRouteImport.update({
  id: '/api/meetings/',
  path: '/api/meetings/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConversationsIndexRoute = ApiConversationsIndexRouteImport.update({
  id: '/api/conversations/',
  path: '/api/conversations/',
  getParentRoute: () => rootRouteImport,
} as any)
const StartupsIdDueDiligenceRoute = StartupsIdDueDiligenceRouteImport.update({
  id: '/due-diligence',
  path: '/due-diligence',
  getParentRoute: () => StartupsIdRoute,
} as any)
const StartupsIdChatRoute = StartupsIdChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => StartupsIdRoute,
} as any)
const FounderStartupsNewRoute = FounderStartupsNewRouteImport.update({
  id: '/founder/startups/new',
  path: '/founder/startups/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWatchlistIdRoute = ApiWatchlistIdRouteImport.update({
  id: '/api/watchlist/$id',
  path: '/api/watchlist/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStartupsDiscoverRoute = ApiStartupsDiscoverRouteImport.update({
  id: '/api/startups/discover',
  path: '/api/startups/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStartupsIdRoute = ApiStartupsIdRouteImport.update({
  id: '/api/startups/$id',
  path: '/api/startups/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSettingsProfileRoute = ApiSettingsProfileRouteImport.update({
  id: '/api/settings/profile',
  path: '/api/settings/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPitchDeckUploadRoute = ApiPitchDeckUploadRouteImport.update({
  id: '/api/pitch-deck/upload',
  path: '/api/pitch-deck/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPitchDeckListRoute = ApiPitchDeckListRouteImport.update({
  id: '/api/pitch-deck/list',
  path: '/api/pitch-deck/list',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNotificationsIdRoute = ApiNotificationsIdRouteImport.update({
  id: '/api/notifications/$id',
  path: '/api/notifications/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMeetingsIdRoute = ApiMeetingsIdRouteImport.update({
  id: '/api/meetings/$id',
  path: '/api/meetings/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInvestorProfileRoute = ApiInvestorProfileRouteImport.update({
  id: '/api/investor/profile',
  path: '/api/investor/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFounderProfileRoute = ApiFounderProfileRouteImport.update({
  id: '/api/founder/profile',
  path: '/api/founder/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthUserRoute = ApiAuthUserRouteImport.update({
  id: '/api/auth/user',
  path: '/api/auth/user',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthRoleRoute = ApiAuthRoleRouteImport.update({
  id: '/api/auth/role',
  path: '/api/auth/role',
  getParentRoute: () => rootRouteImport,
} as any)
const FounderStartupsIdImproveRoute =
  FounderStartupsIdImproveRouteImport.update({
    id: '/founder/startups/$id/improve',
    path: '/founder/startups/$id/improve',
    getParentRoute: () => rootRouteImport,
  } as any)
const FounderStartupsIdEditRoute = FounderStartupsIdEditRouteImport.update({
  id: '/founder/startups/$id/edit',
  path: '/founder/startups/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStartupsIdImproveRoute = ApiStartupsIdImproveRouteImport.update({
  id: '/improve',
  path: '/improve',
  getParentRoute: () => ApiStartupsIdRoute,
} as any)
const ApiStartupsIdChatRoute = ApiStartupsIdChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => ApiStartupsIdRoute,
} as any)
const ApiStartupsIdAnalyzeRoute = ApiStartupsIdAnalyzeRouteImport.update({
  id: '/analyze',
  path: '/analyze',
  getParentRoute: () => ApiStartupsIdRoute,
} as any)
const ApiConversationsIdMessagesRoute =
  ApiConversationsIdMessagesRouteImport.update({
    id: '/api/conversations/$id/messages',
    path: '/api/conversations/$id/messages',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/messages': typeof MessagesRoute
  '/select-role': typeof SelectRoleRoute
  '/settings': typeof SettingsRoute
  '/api/callback': typeof ApiCallbackRoute
  '/api/login': typeof ApiLoginRoute
  '/api/logout': typeof ApiLogoutRoute
  '/api/matches': typeof ApiMatchesRoute
  '/founder/dashboard': typeof FounderDashboardRoute
  '/founder/meetings': typeof FounderMeetingsRoute
  '/founder/pitch-decks': typeof FounderPitchDecksRoute
  '/investor/dashboard': typeof InvestorDashboardRoute
  '/investor/discover': typeof InvestorDiscoverRoute
  '/investor/due-diligence': typeof InvestorDueDiligenceRoute
  '/investor/meetings': typeof InvestorMeetingsRoute
  '/investor/portfolio': typeof InvestorPortfolioRoute
  '/investor/watchlist': typeof InvestorWatchlistRoute
  '/startups/$id': typeof StartupsIdRouteWithChildren
  '/api/auth/role': typeof ApiAuthRoleRoute
  '/api/auth/user': typeof ApiAuthUserRoute
  '/api/founder/profile': typeof ApiFounderProfileRoute
  '/api/investor/profile': typeof ApiInvestorProfileRoute
  '/api/meetings/$id': typeof ApiMeetingsIdRoute
  '/api/notifications/$id': typeof ApiNotificationsIdRoute
  '/api/pitch-deck/list': typeof ApiPitchDeckListRoute
  '/api/pitch-deck/upload': typeof ApiPitchDeckUploadRoute
  '/api/settings/profile': typeof ApiSettingsProfileRoute
  '/api/startups/$id': typeof ApiStartupsIdRouteWithChildren
  '/api/startups/discover': typeof ApiStartupsDiscoverRoute
  '/api/watchlist/$id': typeof ApiWatchlistIdRoute
  '/founder/startups/new': typeof FounderStartupsNewRoute
  '/startups/$id/chat': typeof StartupsIdChatRoute
  '/startups/$id/due-diligence': typeof StartupsIdDueDiligenceRoute
  '/api/conversations/': typeof ApiConversationsIndexRoute
  '/api/meetings/': typeof ApiMeetingsIndexRoute
  '/api/notifications/': typeof ApiNotificationsIndexRoute
  '/api/pitch-deck/': typeof ApiPitchDeckIndexRoute
  '/api/startups/': typeof ApiStartupsIndexRoute
  '/api/watchlist/': typeof ApiWatchlistIndexRoute
  '/founder/startups/': typeof FounderStartupsIndexRoute
  '/api/conversations/$id/messages': typeof ApiConversationsIdMessagesRoute
  '/api/startups/$id/analyze': typeof ApiStartupsIdAnalyzeRoute
  '/api/startups/$id/chat': typeof ApiStartupsIdChatRoute
  '/api/startups/$id/improve': typeof ApiStartupsIdImproveRoute
  '/founder/startups/$id/edit': typeof FounderStartupsIdEditRoute
  '/founder/startups/$id/improve': typeof FounderStartupsIdImproveRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/messages': typeof MessagesRoute
  '/select-role': typeof SelectRoleRoute
  '/settings': typeof SettingsRoute
  '/api/callback': typeof ApiCallbackRoute
  '/api/login': typeof ApiLoginRoute
  '/api/logout': typeof ApiLogoutRoute
  '/api/matches': typeof ApiMatchesRoute
  '/founder/dashboard': typeof FounderDashboardRoute
  '/founder/meetings': typeof FounderMeetingsRoute
  '/founder/pitch-decks': typeof FounderPitchDecksRoute
  '/investor/dashboard': typeof InvestorDashboardRoute
  '/investor/discover': typeof InvestorDiscoverRoute
  '/investor/due-diligence': typeof InvestorDueDiligenceRoute
  '/investor/meetings': typeof InvestorMeetingsRoute
  '/investor/portfolio': typeof InvestorPortfolioRoute
  '/investor/watchlist': typeof InvestorWatchlistRoute
  '/startups/$id': typeof StartupsIdRouteWithChildren
  '/api/auth/role': typeof ApiAuthRoleRoute
  '/api/auth/user': typeof ApiAuthUserRoute
  '/api/founder/profile': typeof ApiFounderProfileRoute
  '/api/investor/profile': typeof ApiInvestorProfileRoute
  '/api/meetings/$id': typeof ApiMeetingsIdRoute
  '/api/notifications/$id': typeof ApiNotificationsIdRoute
  '/api/pitch-deck/list': typeof ApiPitchDeckListRoute
  '/api/pitch-deck/upload': typeof ApiPitchDeckUploadRoute
  '/api/settings/profile': typeof ApiSettingsProfileRoute
  '/api/startups/$id': typeof ApiStartupsIdRouteWithChildren
  '/api/startups/discover': typeof ApiStartupsDiscoverRoute
  '/api/watchlist/$id': typeof ApiWatchlistIdRoute
  '/founder/startups/new': typeof FounderStartupsNewRoute
  '/startups/$id/chat': typeof StartupsIdChatRoute
  '/startups/$id/due-diligence': typeof StartupsIdDueDiligenceRoute
  '/api/conversations': typeof ApiConversationsIndexRoute
  '/api/meetings': typeof ApiMeetingsIndexRoute
  '/api/notifications': typeof ApiNotificationsIndexRoute
  '/api/pitch-deck': typeof ApiPitchDeckIndexRoute
  '/api/startups': typeof ApiStartupsIndexRoute
  '/api/watchlist': typeof ApiWatchlistIndexRoute
  '/founder/startups': typeof FounderStartupsIndexRoute
  '/api/conversations/$id/messages': typeof ApiConversationsIdMessagesRoute
  '/api/startups/$id/analyze': typeof ApiStartupsIdAnalyzeRoute
  '/api/startups/$id/chat': typeof ApiStartupsIdChatRoute
  '/api/startups/$id/improve': typeof ApiStartupsIdImproveRoute
  '/founder/startups/$id/edit': typeof FounderStartupsIdEditRoute
  '/founder/startups/$id/improve': typeof FounderStartupsIdImproveRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/messages': typeof MessagesRoute
  '/select-role': typeof SelectRoleRoute
  '/settings': typeof SettingsRoute
  '/api/callback': typeof ApiCallbackRoute
  '/api/login': typeof ApiLoginRoute
  '/api/logout': typeof ApiLogoutRoute
  '/api/matches': typeof ApiMatchesRoute
  '/founder/dashboard': typeof FounderDashboardRoute
  '/founder/meetings': typeof FounderMeetingsRoute
  '/founder/pitch-decks': typeof FounderPitchDecksRoute
  '/investor/dashboard': typeof InvestorDashboardRoute
  '/investor/discover': typeof InvestorDiscoverRoute
  '/investor/due-diligence': typeof InvestorDueDiligenceRoute
  '/investor/meetings': typeof InvestorMeetingsRoute
  '/investor/portfolio': typeof InvestorPortfolioRoute
  '/investor/watchlist': typeof InvestorWatchlistRoute
  '/startups/$id': typeof StartupsIdRouteWithChildren
  '/api/auth/role': typeof ApiAuthRoleRoute
  '/api/auth/user': typeof ApiAuthUserRoute
  '/api/founder/profile': typeof ApiFounderProfileRoute
  '/api/investor/profile': typeof ApiInvestorProfileRoute
  '/api/meetings/$id': typeof ApiMeetingsIdRoute
  '/api/notifications/$id': typeof ApiNotificationsIdRoute
  '/api/pitch-deck/list': typeof ApiPitchDeckListRoute
  '/api/pitch-deck/upload': typeof ApiPitchDeckUploadRoute
  '/api/settings/profile': typeof ApiSettingsProfileRoute
  '/api/startups/$id': typeof ApiStartupsIdRouteWithChildren
  '/api/startups/discover': typeof ApiStartupsDiscoverRoute
  '/api/watchlist/$id': typeof ApiWatchlistIdRoute
  '/founder/startups/new': typeof FounderStartupsNewRoute
  '/startups/$id/chat': typeof StartupsIdChatRoute
  '/startups/$id/due-diligence': typeof StartupsIdDueDiligenceRoute
  '/api/conversations/': typeof ApiConversationsIndexRoute
  '/api/meetings/': typeof ApiMeetingsIndexRoute
  '/api/notifications/': typeof ApiNotificationsIndexRoute
  '/api/pitch-deck/': typeof ApiPitchDeckIndexRoute
  '/api/startups/': typeof ApiStartupsIndexRoute
  '/api/watchlist/': typeof ApiWatchlistIndexRoute
  '/founder/startups/': typeof FounderStartupsIndexRoute
  '/api/conversations/$id/messages': typeof ApiConversationsIdMessagesRoute
  '/api/startups/$id/analyze': typeof ApiStartupsIdAnalyzeRoute
  '/api/startups/$id/chat': typeof ApiStartupsIdChatRoute
  '/api/startups/$id/improve': typeof ApiStartupsIdImproveRoute
  '/founder/startups/$id/edit': typeof FounderStartupsIdEditRoute
  '/founder/startups/$id/improve': typeof FounderStartupsIdImproveRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/messages'
    | '/select-role'
    | '/settings'
    | '/api/callback'
    | '/api/login'
    | '/api/logout'
    | '/api/matches'
    | '/founder/dashboard'
    | '/founder/meetings'
    | '/founder/pitch-decks'
    | '/investor/dashboard'
    | '/investor/discover'
    | '/investor/due-diligence'
    | '/investor/meetings'
    | '/investor/portfolio'
    | '/investor/watchlist'
    | '/startups/$id'
    | '/api/auth/role'
    | '/api/auth/user'
    | '/api/founder/profile'
    | '/api/investor/profile'
    | '/api/meetings/$id'
    | '/api/notifications/$id'
    | '/api/pitch-deck/list'
    | '/api/pitch-deck/upload'
    | '/api/settings/profile'
    | '/api/startups/$id'
    | '/api/startups/discover'
    | '/api/watchlist/$id'
    | '/founder/startups/new'
    | '/startups/$id/chat'
    | '/startups/$id/due-diligence'
    | '/api/conversations/'
    | '/api/meetings/'
    | '/api/notifications/'
    | '/api/pitch-deck/'
    | '/api/startups/'
    | '/api/watchlist/'
    | '/founder/startups/'
    | '/api/conversations/$id/messages'
    | '/api/startups/$id/analyze'
    | '/api/startups/$id/chat'
    | '/api/startups/$id/improve'
    | '/founder/startups/$id/edit'
    | '/founder/startups/$id/improve'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/messages'
    | '/select-role'
    | '/settings'
    | '/api/callback'
    | '/api/login'
    | '/api/logout'
    | '/api/matches'
    | '/founder/dashboard'
    | '/founder/meetings'
    | '/founder/pitch-decks'
    | '/investor/dashboard'
    | '/investor/discover'
    | '/investor/due-diligence'
    | '/investor/meetings'
    | '/investor/portfolio'
    | '/investor/watchlist'
    | '/startups/$id'
    | '/api/auth/role'
    | '/api/auth/user'
    | '/api/founder/profile'
    | '/api/investor/profile'
    | '/api/meetings/$id'
    | '/api/notifications/$id'
    | '/api/pitch-deck/list'
    | '/api/pitch-deck/upload'
    | '/api/settings/profile'
    | '/api/startups/$id'
    | '/api/startups/discover'
    | '/api/watchlist/$id'
    | '/founder/startups/new'
    | '/startups/$id/chat'
    | '/startups/$id/due-diligence'
    | '/api/conversations'
    | '/api/meetings'
    | '/api/notifications'
    | '/api/pitch-deck'
    | '/api/startups'
    | '/api/watchlist'
    | '/founder/startups'
    | '/api/conversations/$id/messages'
    | '/api/startups/$id/analyze'
    | '/api/startups/$id/chat'
    | '/api/startups/$id/improve'
    | '/founder/startups/$id/edit'
    | '/founder/startups/$id/improve'
  id:
    | '__root__'
    | '/'
    | '/messages'
    | '/select-role'
    | '/settings'
    | '/api/callback'
    | '/api/login'
    | '/api/logout'
    | '/api/matches'
    | '/founder/dashboard'
    | '/founder/meetings'
    | '/founder/pitch-decks'
    | '/investor/dashboard'
    | '/investor/discover'
    | '/investor/due-diligence'
    | '/investor/meetings'
    | '/investor/portfolio'
    | '/investor/watchlist'
    | '/startups/$id'
    | '/api/auth/role'
    | '/api/auth/user'
    | '/api/founder/profile'
    | '/api/investor/profile'
    | '/api/meetings/$id'
    | '/api/notifications/$id'
    | '/api/pitch-deck/list'
    | '/api/pitch-deck/upload'
    | '/api/settings/profile'
    | '/api/startups/$id'
    | '/api/startups/discover'
    | '/api/watchlist/$id'
    | '/founder/startups/new'
    | '/startups/$id/chat'
    | '/startups/$id/due-diligence'
    | '/api/conversations/'
    | '/api/meetings/'
    | '/api/notifications/'
    | '/api/pitch-deck/'
    | '/api/startups/'
    | '/api/watchlist/'
    | '/founder/startups/'
    | '/api/conversations/$id/messages'
    | '/api/startups/$id/analyze'
    | '/api/startups/$id/chat'
    | '/api/startups/$id/improve'
    | '/founder/startups/$id/edit'
    | '/founder/startups/$id/improve'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MessagesRoute: typeof MessagesRoute
  SelectRoleRoute: typeof SelectRoleRoute
  SettingsRoute: typeof SettingsRoute
  ApiCallbackRoute: typeof ApiCallbackRoute
  ApiLoginRoute: typeof ApiLoginRoute
  ApiLogoutRoute: typeof ApiLogoutRoute
  ApiMatchesRoute: typeof ApiMatchesRoute
  FounderDashboardRoute: typeof FounderDashboardRoute
  FounderMeetingsRoute: typeof FounderMeetingsRoute
  FounderPitchDecksRoute: typeof FounderPitchDecksRoute
  InvestorDashboardRoute: typeof InvestorDashboardRoute
  InvestorDiscoverRoute: typeof InvestorDiscoverRoute
  InvestorDueDiligenceRoute: typeof InvestorDueDiligenceRoute
  InvestorMeetingsRoute: typeof InvestorMeetingsRoute
  InvestorPortfolioRoute: typeof InvestorPortfolioRoute
  InvestorWatchlistRoute: typeof InvestorWatchlistRoute
  StartupsIdRoute: typeof StartupsIdRouteWithChildren
  ApiAuthRoleRoute: typeof ApiAuthRoleRoute
  ApiAuthUserRoute: typeof ApiAuthUserRoute
  ApiFounderProfileRoute: typeof ApiFounderProfileRoute
  ApiInvestorProfileRoute: typeof ApiInvestorProfileRoute
  ApiMeetingsIdRoute: typeof ApiMeetingsIdRoute
  ApiNotificationsIdRoute: typeof ApiNotificationsIdRoute
  ApiPitchDeckListRoute: typeof ApiPitchDeckListRoute
  ApiPitchDeckUploadRoute: typeof ApiPitchDeckUploadRoute
  ApiSettingsProfileRoute: typeof ApiSettingsProfileRoute
  ApiStartupsIdRoute: typeof ApiStartupsIdRouteWithChildren
  ApiStartupsDiscoverRoute: typeof ApiStartupsDiscoverRoute
  ApiWatchlistIdRoute: typeof ApiWatchlistIdRoute
  FounderStartupsNewRoute: typeof FounderStartupsNewRoute
  ApiConversationsIndexRoute: typeof ApiConversationsIndexRoute
  ApiMeetingsIndexRoute: typeof ApiMeetingsIndexRoute
  ApiNotificationsIndexRoute: typeof ApiNotificationsIndexRoute
  ApiPitchDeckIndexRoute: typeof ApiPitchDeckIndexRoute
  ApiStartupsIndexRoute: typeof ApiStartupsIndexRoute
  ApiWatchlistIndexRoute: typeof ApiWatchlistIndexRoute
  FounderStartupsIndexRoute: typeof FounderStartupsIndexRoute
  ApiConversationsIdMessagesRoute: typeof ApiConversationsIdMessagesRoute
  FounderStartupsIdEditRoute: typeof FounderStartupsIdEditRoute
  FounderStartupsIdImproveRoute: typeof FounderStartupsIdImproveRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/select-role': {
      id: '/select-role'
      path: '/select-role'
      fullPath: '/select-role'
      preLoaderRoute: typeof SelectRoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/startups/$id': {
      id: '/startups/$id'
      path: '/startups/$id'
      fullPath: '/startups/$id'
      preLoaderRoute: typeof StartupsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investor/watchlist': {
      id: '/investor/watchlist'
      path: '/investor/watchlist'
      fullPath: '/investor/watchlist'
      preLoaderRoute: typeof InvestorWatchlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investor/portfolio': {
      id: '/investor/portfolio'
      path: '/investor/portfolio'
      fullPath: '/investor/portfolio'
      preLoaderRoute: typeof InvestorPortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investor/meetings': {
      id: '/investor/meetings'
      path: '/investor/meetings'
      fullPath: '/investor/meetings'
      preLoaderRoute: typeof InvestorMeetingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investor/due-diligence': {
      id: '/investor/due-diligence'
      path: '/investor/due-diligence'
      fullPath: '/investor/due-diligence'
      preLoaderRoute: typeof InvestorDueDiligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investor/discover': {
      id: '/investor/discover'
      path: '/investor/discover'
      fullPath: '/investor/discover'
      preLoaderRoute: typeof InvestorDiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investor/dashboard': {
      id: '/investor/dashboard'
      path: '/investor/dashboard'
      fullPath: '/investor/dashboard'
      preLoaderRoute: typeof InvestorDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/founder/pitch-decks': {
      id: '/founder/pitch-decks'
      path: '/founder/pitch-decks'
      fullPath: '/founder/pitch-decks'
      preLoaderRoute: typeof FounderPitchDecksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/founder/meetings': {
      id: '/founder/meetings'
      path: '/founder/meetings'
      fullPath: '/founder/meetings'
      preLoaderRoute: typeof FounderMeetingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/founder/dashboard': {
      id: '/founder/dashboard'
      path: '/founder/dashboard'
      fullPath: '/founder/dashboard'
      preLoaderRoute: typeof FounderDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/matches': {
      id: '/api/matches'
      path: '/api/matches'
      fullPath: '/api/matches'
      preLoaderRoute: typeof ApiMatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/logout': {
      id: '/api/logout'
      path: '/api/logout'
      fullPath: '/api/logout'
      preLoaderRoute: typeof ApiLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/login': {
      id: '/api/login'
      path: '/api/login'
      fullPath: '/api/login'
      preLoaderRoute: typeof ApiLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/callback': {
      id: '/api/callback'
      path: '/api/callback'
      fullPath: '/api/callback'
      preLoaderRoute: typeof ApiCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/founder/startups/': {
      id: '/founder/startups/'
      path: '/founder/startups'
      fullPath: '/founder/startups/'
      preLoaderRoute: typeof FounderStartupsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/watchlist/': {
      id: '/api/watchlist/'
      path: '/api/watchlist'
      fullPath: '/api/watchlist/'
      preLoaderRoute: typeof ApiWatchlistIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/startups/': {
      id: '/api/startups/'
      path: '/api/startups'
      fullPath: '/api/startups/'
      preLoaderRoute: typeof ApiStartupsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pitch-deck/': {
      id: '/api/pitch-deck/'
      path: '/api/pitch-deck'
      fullPath: '/api/pitch-deck/'
      preLoaderRoute: typeof ApiPitchDeckIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notifications/': {
      id: '/api/notifications/'
      path: '/api/notifications'
      fullPath: '/api/notifications/'
      preLoaderRoute: typeof ApiNotificationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/meetings/': {
      id: '/api/meetings/'
      path: '/api/meetings'
      fullPath: '/api/meetings/'
      preLoaderRoute: typeof ApiMeetingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/conversations/': {
      id: '/api/conversations/'
      path: '/api/conversations'
      fullPath: '/api/conversations/'
      preLoaderRoute: typeof ApiConversationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/startups/$id/due-diligence': {
      id: '/startups/$id/due-diligence'
      path: '/due-diligence'
      fullPath: '/startups/$id/due-diligence'
      preLoaderRoute: typeof StartupsIdDueDiligenceRouteImport
      parentRoute: typeof StartupsIdRoute
    }
    '/startups/$id/chat': {
      id: '/startups/$id/chat'
      path: '/chat'
      fullPath: '/startups/$id/chat'
      preLoaderRoute: typeof StartupsIdChatRouteImport
      parentRoute: typeof StartupsIdRoute
    }
    '/founder/startups/new': {
      id: '/founder/startups/new'
      path: '/founder/startups/new'
      fullPath: '/founder/startups/new'
      preLoaderRoute: typeof FounderStartupsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/watchlist/$id': {
      id: '/api/watchlist/$id'
      path: '/api/watchlist/$id'
      fullPath: '/api/watchlist/$id'
      preLoaderRoute: typeof ApiWatchlistIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/startups/discover': {
      id: '/api/startups/discover'
      path: '/api/startups/discover'
      fullPath: '/api/startups/discover'
      preLoaderRoute: typeof ApiStartupsDiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/startups/$id': {
      id: '/api/startups/$id'
      path: '/api/startups/$id'
      fullPath: '/api/startups/$id'
      preLoaderRoute: typeof ApiStartupsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/settings/profile': {
      id: '/api/settings/profile'
      path: '/api/settings/profile'
      fullPath: '/api/settings/profile'
      preLoaderRoute: typeof ApiSettingsProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pitch-deck/upload': {
      id: '/api/pitch-deck/upload'
      path: '/api/pitch-deck/upload'
      fullPath: '/api/pitch-deck/upload'
      preLoaderRoute: typeof ApiPitchDeckUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pitch-deck/list': {
      id: '/api/pitch-deck/list'
      path: '/api/pitch-deck/list'
      fullPath: '/api/pitch-deck/list'
      preLoaderRoute: typeof ApiPitchDeckListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notifications/$id': {
      id: '/api/notifications/$id'
      path: '/api/notifications/$id'
      fullPath: '/api/notifications/$id'
      preLoaderRoute: typeof ApiNotificationsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/meetings/$id': {
      id: '/api/meetings/$id'
      path: '/api/meetings/$id'
      fullPath: '/api/meetings/$id'
      preLoaderRoute: typeof ApiMeetingsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/investor/profile': {
      id: '/api/investor/profile'
      path: '/api/investor/profile'
      fullPath: '/api/investor/profile'
      preLoaderRoute: typeof ApiInvestorProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/founder/profile': {
      id: '/api/founder/profile'
      path: '/api/founder/profile'
      fullPath: '/api/founder/profile'
      preLoaderRoute: typeof ApiFounderProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/user': {
      id: '/api/auth/user'
      path: '/api/auth/user'
      fullPath: '/api/auth/user'
      preLoaderRoute: typeof ApiAuthUserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/role': {
      id: '/api/auth/role'
      path: '/api/auth/role'
      fullPath: '/api/auth/role'
      preLoaderRoute: typeof ApiAuthRoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/founder/startups/$id/improve': {
      id: '/founder/startups/$id/improve'
      path: '/founder/startups/$id/improve'
      fullPath: '/founder/startups/$id/improve'
      preLoaderRoute: typeof FounderStartupsIdImproveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/founder/startups/$id/edit': {
      id: '/founder/startups/$id/edit'
      path: '/founder/startups/$id/edit'
      fullPath: '/founder/startups/$id/edit'
      preLoaderRoute: typeof FounderStartupsIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/startups/$id/improve': {
      id: '/api/startups/$id/improve'
      path: '/improve'
      fullPath: '/api/startups/$id/improve'
      preLoaderRoute: typeof ApiStartupsIdImproveRouteImport
      parentRoute: typeof ApiStartupsIdRoute
    }
    '/api/startups/$id/chat': {
      id: '/api/startups/$id/chat'
      path: '/chat'
      fullPath: '/api/startups/$id/chat'
      preLoaderRoute: typeof ApiStartupsIdChatRouteImport
      parentRoute: typeof ApiStartupsIdRoute
    }
    '/api/startups/$id/analyze': {
      id: '/api/startups/$id/analyze'
      path: '/analyze'
      fullPath: '/api/startups/$id/analyze'
      preLoaderRoute: typeof ApiStartupsIdAnalyzeRouteImport
      parentRoute: typeof ApiStartupsIdRoute
    }
    '/api/conversations/$id/messages': {
      id: '/api/conversations/$id/messages'
      path: '/api/conversations/$id/messages'
      fullPath: '/api/conversations/$id/messages'
      preLoaderRoute: typeof ApiConversationsIdMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface StartupsIdRouteChildren {
  StartupsIdChatRoute: typeof StartupsIdChatRoute
  StartupsIdDueDiligenceRoute: typeof StartupsIdDueDiligenceRoute
}

const StartupsIdRouteChildren: StartupsIdRouteChildren = {
  StartupsIdChatRoute: StartupsIdChatRoute,
  StartupsIdDueDiligenceRoute: StartupsIdDueDiligenceRoute,
}

const StartupsIdRouteWithChildren = StartupsIdRoute._addFileChildren(
  StartupsIdRouteChildren,
)

interface ApiStartupsIdRouteChildren {
  ApiStartupsIdAnalyzeRoute: typeof ApiStartupsIdAnalyzeRoute
  ApiStartupsIdChatRoute: typeof ApiStartupsIdChatRoute
  ApiStartupsIdImproveRoute: typeof ApiStartupsIdImproveRoute
}

const ApiStartupsIdRouteChildren: ApiStartupsIdRouteChildren = {
  ApiStartupsIdAnalyzeRoute: ApiStartupsIdAnalyzeRoute,
  ApiStartupsIdChatRoute: ApiStartupsIdChatRoute,
  ApiStartupsIdImproveRoute: ApiStartupsIdImproveRoute,
}

const ApiStartupsIdRouteWithChildren = ApiStartupsIdRoute._addFileChildren(
  ApiStartupsIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MessagesRoute: MessagesRoute,
  SelectRoleRoute: SelectRoleRoute,
  SettingsRoute: SettingsRoute,
  ApiCallbackRoute: ApiCallbackRoute,
  ApiLoginRoute: ApiLoginRoute,
  ApiLogoutRoute: ApiLogoutRoute,
  ApiMatchesRoute: ApiMatchesRoute,
  FounderDashboardRoute: FounderDashboardRoute,
  FounderMeetingsRoute: FounderMeetingsRoute,
  FounderPitchDecksRoute: FounderPitchDecksRoute,
  InvestorDashboardRoute: InvestorDashboardRoute,
  InvestorDiscoverRoute: InvestorDiscoverRoute,
  InvestorDueDiligenceRoute: InvestorDueDiligenceRoute,
  InvestorMeetingsRoute: InvestorMeetingsRoute,
  InvestorPortfolioRoute: InvestorPortfolioRoute,
  InvestorWatchlistRoute: InvestorWatchlistRoute,
  StartupsIdRoute: StartupsIdRouteWithChildren,
  ApiAuthRoleRoute: ApiAuthRoleRoute,
  ApiAuthUserRoute: ApiAuthUserRoute,
  ApiFounderProfileRoute: ApiFounderProfileRoute,
  ApiInvestorProfileRoute: ApiInvestorProfileRoute,
  ApiMeetingsIdRoute: ApiMeetingsIdRoute,
  ApiNotificationsIdRoute: ApiNotificationsIdRoute,
  ApiPitchDeckListRoute: ApiPitchDeckListRoute,
  ApiPitchDeckUploadRoute: ApiPitchDeckUploadRoute,
  ApiSettingsProfileRoute: ApiSettingsProfileRoute,
  ApiStartupsIdRoute: ApiStartupsIdRouteWithChildren,
  ApiStartupsDiscoverRoute: ApiStartupsDiscoverRoute,
  ApiWatchlistIdRoute: ApiWatchlistIdRoute,
  FounderStartupsNewRoute: FounderStartupsNewRoute,
  ApiConversationsIndexRoute: ApiConversationsIndexRoute,
  ApiMeetingsIndexRoute: ApiMeetingsIndexRoute,
  ApiNotificationsIndexRoute: ApiNotificationsIndexRoute,
  ApiPitchDeckIndexRoute: ApiPitchDeckIndexRoute,
  ApiStartupsIndexRoute: ApiStartupsIndexRoute,
  ApiWatchlistIndexRoute: ApiWatchlistIndexRoute,
  FounderStartupsIndexRoute: FounderStartupsIndexRoute,
  ApiConversationsIdMessagesRoute: ApiConversationsIdMessagesRoute,
  FounderStartupsIdEditRoute: FounderStartupsIdEditRoute,
  FounderStartupsIdImproveRoute: FounderStartupsIdImproveRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
